version: "3.8"
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
      - "8883:8883"
    restart: always

  mysql db:
    image: mysql/mysql:latest
    container_name: mysql_cont
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: rootpass
      - MYSQL_DATABASE: mysql_db
      - MYSQL_USER: m_user
      - MYSQL_PASSWORD: m_pass
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
