services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
      - "8883:8883"
    environment:
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=Tatimari13
    restart: always

  mysql_data:
    image: mysql:latest
    container_name: mysql_cont
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: m_user
      MYSQL_PASSWORD: m_pass
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: mysql_data
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql_data

  consumidor:
    build: ./consumidor 
    container_name: consumidor_mqtt
    depends_on: 
      - emqx
      - mysql_data
    restart: always

volumes:
  mysql_data: {}