version: "3.8" 
services: 
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports: 
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
      - "8883:8883"
    restart: always
