import paho.mqtt.client as mqtt  # essa biblioteca faz a minha "ponte" entre o código python e o broker mqtt que no caso é o emqx :)
import time # biblioteca para trabalhar com o tempo em py, pausar a execução do cod, registrar data/hora...
